INSERT INTO countries (id, name) 
VALUES
    (1, 'Albania'),
    (2, 'Andorra'),
    (3, 'Armenia'),
    (4, 'Australia'),
    (5, 'Austria'),
    (6, 'Azerbaijan'),
    (7, 'Belarus'),
    (8, 'Belgium'),
    (9, 'Bosnia and Herzegovina'),
    (10, 'Bulgaria'),
    (11, 'Croatia'),
    (12, 'Cyprus'),
    (13, 'Czechia'),
    (14, 'Denmark'),
    (15, 'Estonia'),
    (16, 'Finland'),
    (17, 'France'),
    (18, 'Georgia'),
    (19, 'Germany'),
    (20, 'Greece'),
    (21, 'Hungary'),
    (22, 'Iceland'),
    (23, 'Ireland'),
    (24, 'Israel'),
    (25, 'Italy'),
    (26, 'Kazakhstan'),
    (27, 'Latvia'),
    (28, 'Lithuania'),
    (29, 'Luxembourg'),
    (30, 'Malta'),
    (31, 'Moldova'),
    (32, 'Monaco'),
    (33, 'Montenegro'),
    (34, 'Morocco'),
    (35, 'Netherlands'),
    (36, 'North Macedonia'),
    (37, 'Norway'),
    (38, 'Poland'),
    (39, 'Portugal'),
    (40, 'Romania'),
    (41, 'Russia'),
    (42, 'San Marino'),
    (43, 'Serbia'),
    (44, 'Serbia and Montenegro'),
    (45, 'Slovakia'),
    (46, 'Slovenia'),
    (47, 'Spain'),
    (48, 'Sweden'),
    (49, 'Switzerland'),
    (50, 'Turkey'),
    (51, 'Ukraine'),
    (52, 'United Kingdom'),
    (53, 'Wales'),
    (54, 'Yugoslavia');
